### PR TITLE
docs: fix readme.

### PR DESCRIPTION
**Pull request by zhouaihui**

### CODE REVIEW

**Comment by jovany-wang** [comment]
It still failed to render:
image

**Comment by zhouaihui** [comment]
Click `view file` and it's ok.

image

**Comment by jovany-wang** [comment]
@zhouaihui  I guess the gap is that README is too narrow to render it(see https://github.com/zhouaihui/rayfed/tree/fix/readme) while it's ok in a single rendered page.

Maybe let remove some unnecessary items or we should refactor the table~

**Comment by zhouaihui** [comment]
It's a bug of github? You can check the source file, there is only one "|" here.
image

**Comment by zhouaihui** [comment]
It's a bug of github? You can check the source file, there is only one "|" here.
image

**Review by jovany-wang — APPROVED** [review]

**Pull request merged**
