### PR TITLE
Reset sending queue after `fed.shutdown`

### PR DESCRIPTION
**Pull request by NKcqx**
The send queue won't be cleared when shutting down rayfed, the message left in the queue may be read in the next session, i.e. the next time calling `fed.init` , which is one of the reason what happened in this [issue](https://github.com/secretflow/secretflow/issues/529)

Note that this PR couldn't completely fix that problem because there're also flying request after `fed.shutdown`, will open another PR.

### CODE REVIEW

**Review by zhouaihui — APPROVED** [review]
LGTM

**Review by jovany-wang — CHANGES_REQUESTED** [review]
2 comments:
1. Add a unit test.
2. PR title should be updated to get more detailed, like "Fix repeated sessions bug." or some thing related to what you concretely do.

**Comment by NKcqx** [comment]
> 2 comments:
> 
> 1. Add a unit test.
> 2. PR title should be updated to get more detailed, like "Fix repeated sessions bug." or some thing related to what you concretely do.

Thx for the suggestions ～!

**Review by jovany-wang — APPROVED** [review]

**Comment by jovany-wang** [comment]
Please address the conflicts before merging~

**Review by jovany-wang — APPROVED** [review]
Conflicts were addressed. It could be merged once CI passes.

**Pull request merged**
