### PR TITLE
docs: correct tls config docstring.

### PR DESCRIPTION
**Pull request by zhouaihui**
- Correct tls_config docstring
- Bump to 0.1.1a0 since 0.1.0b1 is shipped already.

### CODE REVIEW

**Comment by jovany-wang** [comment]
It seems that we didn't release `rayfed-0.1.0`.  Then do you think we should start releasing at the point `rayfed-0.1.1`?

**Comment by zhouaihui** [comment]
`secretlfow-rayfed- 0.1.0 `is shipped and it's better that we use 0.1.1 for rayfed.

**Review by jovany-wang — APPROVED** [review]
LGTM.
BTW: When do you think is the best time to release rayfed-0.1.1?

**Comment by zhouaihui** [comment]
> LGTM. BTW: When do you think is the best time to release rayfed-0.1.1?

Do you mean the release version,  not pre-release with alpha/beta?

**Pull request merged**
