### PR TITLE
docs: add api doc.

### LINKED ISSUE #197: Add api docs.
We shall provide public api doc.

### PR DESCRIPTION
**Pull request by zhouaihui**
Close #197

### CODE REVIEW

**Review by NKcqx — APPROVED** [review]
Remarkable improvement. We should keep doing this.

**Review by jovany-wang — APPROVED** [review]
Outstanding work!

**Comment by jovany-wang** [comment]
Does it should be deployed automatically?

**Comment by zhouaihui** [comment]
It did. You can check the latest readthedoc web

**Comment by zhouaihui** [comment]
There is some errors in automatic-deploy, gona fix it in next pr.

**Pull request merged**
